package common;

public enum MessageType {
    GET_FULL_PRICE,
    GET_FULL_PRICE_RESPONSE,
    
    CHECK_PROMOTIONS,
    CHECK_PROMOTIONS_RESPONSE,
    
    VALIDATE_ORDER,
    VALIDATE_ORDER_RESPONSE,
    
    CHECK_CAPACITY,
    CHECK_CAPACITY_RESPONSE,
    
    CONFIRM_PAYMENT,
    CONFIRM_PAYMENT_RESPONSE,
    
    VERIFY_GUIDE,
    VERIFY_GUIDE_RESPONSE,
    
    VERIFY_SUBSCRIBER,
    VERIFY_SUBSCRIBER_RESPONSE,
    
    EXIT_PARK,
    EXIT_PARK_RESPONSE,
    
    GET_VISITOR_REPORT,
    GET_VISITOR_REPORT_RESPONSE,
    
    GET_CANCELLATION_REPORT,
    GET_CANCELLATION_REPORT_RESPONSE,
    
    GET_PARKS_CANCELLATION_REPORT,
    GET_PARKS_CANCELLATION_REPORT_RESPONSE,
    
    GET_TOTAL_VISITOR_REPORT,
    GET_TOTAL_VISITOR_REPORT_RESPONSE,
    
    GET_OCCUPANCY_REPORT,
    GET_OCCUPANCY_REPORT_RESPONSE,
    
    GET_PARKS,
    GET_PARKS_RESPONSE,
    
    REGISTER_FAMILY_SUBSCRIBER,
    REGISTER_SINGLE_SUBSCRIBER,
    REGISTER_GUIDE,
    REGISTRATION_SUCCESS,
    REGISTRATION_FAILED,
    
    SUBMIT_PARAMETER_REQUEST,
    GET_PENDING_PARAMETER_REQUESTS,
    UPDATE_PARAMETER_REQUEST_STATUS,
    REQUEST_SUBMIT_SUCCESS,
    PROMOTION_ACTIVATED_SUCCESS,
    UPDATE_REQUEST_SUCCESS,
    GET_PENDING_REQUESTS_RESPONSE,
    ACTIVATE_PROMOTION,
    PROMOTION_ACTIVATED_FAILED,
    UPDATE_REQUEST_FAILED,
    REQUEST_SUBMIT_FAILED,
    
    
    
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    
}