package common;

public enum MessageType {
    GET_FULL_PRICE,
    GET_FULL_PRICE_RESPONSE,
    
    CHECK_PROMOTIONS,
    CHECK_PROMOTIONS_RESPONSE,
    
    VALIDATE_ORDER,
    VALIDATE_ORDER_RESPONSE,
    
    CHECK_CAPACITY,
    CHECK_CAPACITY_RESPONSE,
    
    CONFIRM_PAYMENT,
    CONFIRM_PAYMENT_RESPONSE,
    
    VERIFY_GUIDE,
    VERIFY_GUIDE_RESPONSE,
    
    VERIFY_SUBSCRIBER,
    VERIFY_SUBSCRIBER_RESPONSE,
    
    EXIT_PARK,
    EXIT_PARK_RESPONSE,
    
    GET_VISITOR_REPORT,
    GET_VISITOR_REPORT_RESPONSE,
    
    GET_CANCELLATION_REPORT,
    GET_CANCELLATION_REPORT_RESPONSE,
    
    GET_PARKS_CANCELLATION_REPORT,
    GET_PARKS_CANCELLATION_REPORT_RESPONSE,
    
    GET_TOTAL_VISITOR_REPORT,
    GET_TOTAL_VISITOR_REPORT_RESPONSE,
    
    GET_OCCUPANCY_REPORT,
    GET_OCCUPANCY_REPORT_RESPONSE,
    
    GET_PARKS,
    GET_PARKS_RESPONSE,
}